version: "3.8"

services:

  db:
    build: ./db
    environment:
      POSTGRES_USER: ${TTBOT_DATABASE_USER:-toptracks}
      POSTGRES_PASSWORD: ${TTBOT_DATABASE_PASS:-toptracks}
      POSTGRES_DB: toptracksbot
      PGDATA: /var/toptracksbot/data
    volumes:
      - ~/.toptracksbot/data:/var/toptracksbot/data
    ports:
      - ${TTBOT_DATABASE_PORT:-5432}:5432
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  bot:
    build: ./bot
    env_file: .env
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  test_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${TTBOT_DATABASE_USER:-toptracks}
      POSTGRES_PASSWORD: ${TTBOT_DATABASE_PASS:-toptracks}
      POSTGRES_DB: toptracksbot
      PGDATA: /var/toptracksbot/data
    profiles:
      - test

  tests:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    environment:
      TTBOT_DATABASE_URI: postgres://${TTBOT_DATABASE_USER:-toptracks}:${TTBOT_DATABASE_PASS:-toptracks}@test_db/toptracksbot
    env_file: .env
    depends_on:
      - test_db
    profiles:
      - test
